### ISSUE TITLE
Small size doesn't work for most of styles

### ISSUE THREAD

**Issue by JobaDiniz** [zeluisping/LoadingIndicators.WPF#3] opened 2016-09-03 13:54 UTC
It would be nice if the loading indicators worked in small sizes...

For example, setting `Height=20` and `Width=20` for _Arc, ArcsRing, Ring_ doesn't matter: the control doesn't respect that size.

Is there a easy way to fix that?

**Comment by 100GPing100** [comment] 2016-09-16 15:39
I can take a look into it, can't promise much due to personal time constraints, but should be able to fix it. Thank you for reporting this!

**Comment by AlexanderHryk** [comment] 2017-01-12 14:07
JobaDiniz, you can also use RenderTransform to change the size of indicators.
kirilpopov, You can use RenderTransform to any style of these indicators without distortion of animation effect

```
<loadin:LoadingIndicator HorizontalAlignment="Left" SpeedRatio="1.0" IsActive="true" Foreground="Red" Style="{DynamicResource LoadingIndicatorArcsStyle}">
            <loadin:LoadingIndicator.RenderTransform>
                <ScaleTransform ScaleX="0.5" ScaleY="0.5" />
            </loadin:LoadingIndicator.RenderTransform>
</loadin:LoadingIndicator>
```

**Comment by 100GPing100** [comment] 2017-01-13 09:34
This is the same issue as #4 , for now you should use the workaround provided by @AlexanderHryk, I'm trying to get some time to work on this and fix this issue.

**Comment by zeluisping** [comment] 2019-08-01 09:48
Closing as duplicate of #4

**Closed by zeluisping** 2019-08-01 09:48 UTC
Labels: Duplicate
